[package]
#[allow(dead_code)]
name = "salvo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo_draw = "0.3.1"
